name: Publicar a Dockerhub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-container:
    runs-on: ubuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{  secrets.DOCKER_PASSWORD  }}

      - name: Extraer metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: asmilex/vin

      - name: build y push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{  steps.meta.outputs.tags  }}
          labels: ${{  steps.meta.output.labels  }}