name: Publicar a Dockerhub
on:
  push:
    branches:
      - 'main'
      - 'objetivo-6'
    tags:
      - 'v*'

jobs:
  dockerfile-changes:
    strategy:
      matrix:
        python_version: [3.8, 3.9, 3.10]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Comprobar qué archivos han cambiado
        id: changed-files
        uses: tj-actions/changed-files@v1.2.0

      - name: Login en Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{  secrets.DOCKER_PASSWORD  }}

      - name: Extraer metadatos (tags, labels) para Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: asmilex/iv

      - name: build y push
        if: |
          contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'pyproject.toml')
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: asmilex/iv:${{ matrix.python_version }}
          labels: ${{  steps.meta.output.labels  }}
          build-args: ${{ matrix.python_version }}

      - name: Sync readme
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{  secrets.DOCKER_USERNAME  }}
          password: ${{  secrets.DOCKER_PASSWORD  }}
          repository: asmilex/iv
          readme: "./README.md"
