name: Aplicar linter

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    container:
      image: asmilex/iv
      options: --user vin_user

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: lint
        run: poetry run task lint
