name: Aplicar linter

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "vin"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          isort-options: "-w 100"
          django: false