name: "Test sobre el código fuente"

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: asmilex:iv

    steps:
      # Vigilar permisos y directorio del checkout.
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Aplicar test
        run: poetry run task lint
