name: "Test sobre el código fuente"

on:
  push:
    branches-ignore: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Aplicar test
        run: docker run -t -v `pwd`:/app/test asmilex/iv